# Generated by Django 6.1.1 on 2026-09-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: D&D, Zenless Zone Zero, Customizado', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_personagem', models.CharField(max_length=150)),
                ('nome_jogo_customizado', models.CharField(blank=True, help_text="Preencha se o Template for 'Customizado'", max_length=100, null=True)),
                ('is_publica', models.BooleanField(default=False, help_text='Marque para expor na plataforma')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.templatejogo')),
            ],
        ),
        migrations.CreateModel(
            name='CampoCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_campo', models.CharField(help_text="Ex: 'Classe', 'Atributo', 'Lore'", max_length=100)),
                ('valor', models.TextField(help_text="Ex: 'Guerreiro', '20', 'História...'")),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='fichas.ficha')),
            ],
        ),
    ]
